In [8]:
import pandas as pd
import numpy as np
import os

In [ ]:
pd.set_option('display.max_columns', 50)

In [3]:
df = pd.read_csv("merged_streaming_data.csv")
df.head()

,id_student,code_module,code_presentation,date,forumng,homepage,oucontent,subpage,url,resource,glossary,dataplus,oucollaborate,quiz,ouelluminate,sharedsubpage,questionnaire,page,externalquiz,ouwiki,dualpane,repeatactivity,folder,htmlactivity,id_assessment,is_banked,score,assessment_type,due_date,weight,module_presentation_length,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration
0,6516,AAA,2014J,-23.0,0,3,23,2,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,269,M,Scotland,HE Qualification,80-90%,55<=,0,60,N,Pass,-52.0,NaN
1,6516,AAA,2014J,-22.0,33,13,34,0,0,2,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,269,M,Scotland,HE Qualification,80-90%,55<=,0,60,N,Pass,-52.0,NaN
2,6516,AAA,2014J,-20.0,13,12,8,1,0,7,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,269,M,Scotland,HE Qualification,80-90%,55<=,0,60,N,Pass,-52.0,NaN
3,6516,AAA,2014J,-17.0,0,2,0,3,2,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,269,M,Scotland,HE Qualification,80-90%,55<=,0,60,N,Pass,-52.0,NaN
4,6516,AAA,2014J,-12.0,1,1,0,0,0,0,0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,269,M,Scotland,HE Qualification,80-90%,55<=,0,60,N,Pass,-52.0,NaN

In [4]:
df.columns

Index(['id_student', 'code_module', 'code_presentation', 'date', 'forumng',
       'homepage', 'oucontent', 'subpage', 'url', 'resource', 'glossary',
       'dataplus', 'oucollaborate', 'quiz', 'ouelluminate', 'sharedsubpage',
       'questionnaire', 'page', 'externalquiz', 'ouwiki', 'dualpane',
       'repeatactivity', 'folder', 'htmlactivity', 'id_assessment',
       'is_banked', 'score', 'assessment_type', 'due_date', 'weight',
       'module_presentation_length', 'gender', 'region', 'highest_education',
       'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits',
       'disability', 'final_result', 'date_registration',
       'date_unregistration'],
      dtype='object')

Add engineered features

In [ ]:
df["relative_submission_date"] = df["due_date"] - df["date"]
df["submission_type"] = np.where(df["relative_submission_date"] < 0, "Late", "Early")

# df.loc[df["id_assessment"].notna(), [
#     "id_student", "date", "id_assessment", "score",
#     "assessment_type", "due_date", "relative_submission_date", "submission_type"
# ]].head()

,id_student,date,id_assessment,score,assessment_type,due_date,relative_submission_date,submission_type
21,6516,17.0,1758.0,60.0,TMA,19.0,2.0,Early
40,6516,51.0,1759.0,48.0,TMA,54.0,3.0,Early
73,6516,116.0,1760.0,63.0,TMA,117.0,1.0,Early
103,6516,164.0,1761.0,61.0,TMA,166.0,2.0,Early
136,6516,210.0,1762.0,77.0,TMA,215.0,5.0,Early

Separate modules and save to csv

In [9]:
# Create a folder to store the CSV files (optional but recommended)
output_folder = "modules_csv"
os.makedirs(output_folder, exist_ok=True)

# Loop over each unique code_module and save separately
for module, df_subset in df.groupby("code_module"):
    filename = f"{output_folder}/{module}_data.csv"
    df_subset.to_csv(filename, index=False)
    print(f"Saved: {filename}")

Saved: modules_csv/AAA_data.csv
Saved: modules_csv/BBB_data.csv
Saved: modules_csv/CCC_data.csv
Saved: modules_csv/DDD_data.csv
Saved: modules_csv/EEE_data.csv
Saved: modules_csv/FFF_data.csv
Saved: modules_csv/GGG_data.csv